version: '3'

services:
  backend: 
    build: .
    image: webapp-backend
    ports: 
      - 127.0.0.1:1234:5000
    volumes:
      - ./python:/app
  nginx: 
    image: nginx:stable-alpine
    ports: 
      - 8090:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./python/templates:/var/www/html
    links: 
      - "backend"